// <auto-generated />
namespace Sordid.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class UserEmail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserEmail));
        
        string IMigrationMetadata.Id
        {
            get { return "201402261946465_UserEmail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
